import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Accounting — TZ tab 12, /accounting. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(12)

export default function Page() {
  return <PageSkeleton num={12} />
}
