/**
 * Writes one route file per TZ page tab.
 *
 * The routes are generated rather than hand-written because they are all the
 * same four lines - the page's identity is its tab number, and everything else
 * comes from `content/tz` and `content/art`. Re-run after the parser.
 *
 *   node scripts/gen-routes.mjs
 *
 * Four tabs do not get a plain route:
 *   01  is the homepage, already built by hand, and is left alone.
 *   39  is the 404 body, which Next wants at app/not-found.tsx.
 *   40-42 are templates for generated detail pages, which live behind the root
 *        slug registry in app/[slug] rather than at a URL of their own.
 */
import fs from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "..")
const pages = JSON.parse(fs.readFileSync(path.join(root, "content/tz/pages.json"), "utf8"))

const SKIP = new Set([1, 39, 40, 41, 42])
let written = 0

for (const page of pages) {
  if (SKIP.has(page.num)) continue
  const slug = page.url.replace(/^\//, "")
  if (!slug || slug.includes("{")) continue

  const dir = path.join(root, "app", slug)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(
    path.join(dir, "page.tsx"),
    `import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** ${page.name} — TZ tab ${String(page.num).padStart(2, "0")}, ${page.url}. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(${page.num})

export default function Page() {
  return <PageSkeleton num={${page.num}} />
}
`,
  )
  written++
}

console.log(`wrote ${written} routes`)
