import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Finance Teams — TZ tab 16, /finance. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(16)

export default function Page() {
  return <PageSkeleton num={16} />
}
