import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Fleets — TZ tab 18, /fleets. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(18)

export default function Page() {
  return <PageSkeleton num={18} />
}
