import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Drivers — TZ tab 15, /drivers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(15)

export default function Page() {
  return <PageSkeleton num={15} />
}
