import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Cookies — TZ tab 38, /cookies. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(38)

export default function Page() {
  return <PageSkeleton num={38} />
}
