import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Carriers — TZ tab 09, /carriers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(9)

export default function Page() {
  return <PageSkeleton num={9} />
}
