import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Owner-Operators — TZ tab 17, /owner-operators. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(17)

export default function Page() {
  return <PageSkeleton num={17} />
}
