import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Support — TZ tab 46, /support. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(46)

export default function Page() {
  return <PageSkeleton num={46} />
}
