import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Pricing — TZ tab 19, /pricing. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(19)

export default function Page() {
  return <PageSkeleton num={19} />
}
