import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Экосистема — TZ tab 02, /products. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(2)

export default function Page() {
  return <PageSkeleton num={2} />
}
