import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Tools — TZ tab 26, /tools. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(26)

export default function Page() {
  return <PageSkeleton num={26} />
}
