import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Case Studies — TZ tab 22, /case-studies. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(22)

export default function Page() {
  return <PageSkeleton num={22} />
}
