import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Login — TZ tab 47, /login. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(47)

export default function Page() {
  return <PageSkeleton num={47} />
}
