import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Roadmap — TZ tab 29, /roadmap. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(29)

export default function Page() {
  return <PageSkeleton num={29} />
}
