import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Demo — TZ tab 35, /demo. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(35)

export default function Page() {
  return <PageSkeleton num={35} />
}
