import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Terms — TZ tab 37, /terms. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(37)

export default function Page() {
  return <PageSkeleton num={37} />
}
