import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Platform — TZ tab 43, /platform. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(43)

export default function Page() {
  return <PageSkeleton num={43} />
}
