import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Broker Intelligence — TZ tab 44, /broker-intelligence. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(44)

export default function Page() {
  return <PageSkeleton num={44} />
}
