import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Press — TZ tab 33, /press. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(33)

export default function Page() {
  return <PageSkeleton num={33} />
}
