import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Careers — TZ tab 32, /careers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(32)

export default function Page() {
  return <PageSkeleton num={32} />
}
