import type { ImgHTMLAttributes } from "react"
import { IMG_DIMENSIONS } from "@/generated/img-dimensions"

/**
 * Drop-in <img> replacement that serves AVIF → WebP with the original PNG/JPG
 * kept as the universal fallback (siblings generated by
 * scripts/transcode-images.mjs). Only `/figma/**` raster paths are upgraded —
 * everything else (SVG, data:, Vite-hashed or external URLs) renders as a plain
 * <img>, so there is never a request for a sibling that doesn't exist.
 *
 * The <picture> wrapper is display:contents, so it is transparent to layout: the
 * inner <img> keeps every class, style and data-attribute and behaves exactly as
 * a bare <img> would (reveal/parallax/positioning all still target it).
 */
type Props = ImgHTMLAttributes<HTMLImageElement> & { src: string }

export function Img({ src, alt = "", ...rest }: Props) {
  // reserve layout space from the intrinsic size (Tailwind preflight keeps
  // height:auto, so these become an aspect-ratio hint — no visual change, but
  // the box is reserved before load → no CLS). Skip if the caller set its own.
  const dim = IMG_DIMENSIONS[src]
  const sized =
    dim && rest.width == null && rest.height == null
      ? { width: dim[0], height: dim[1] }
      : undefined

  const upgradable = src.startsWith("/figma/") && /\.(png|jpe?g)$/i.test(src)
  if (!upgradable) return <img src={src} alt={alt} {...sized} {...rest} />
  const base = src.replace(/\.(png|jpe?g)$/i, "")
  return (
    <picture className="contents">
      <source srcSet={`${base}.avif`} type="image/avif" />
      <source srcSet={`${base}.webp`} type="image/webp" />
      <img src={src} alt={alt} {...sized} {...rest} />
    </picture>
  )
}
