import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Partners — TZ tab 13, /partners. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(13)

export default function Page() {
  return <PageSkeleton num={13} />
}
