import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** About — TZ tab 31, /about. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(31)

export default function Page() {
  return <PageSkeleton num={31} />
}
