import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Trust Center — TZ tab 28, /trust. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(28)

export default function Page() {
  return <PageSkeleton num={28} />
}
