import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Resources — TZ tab 23, /resources. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(23)

export default function Page() {
  return <PageSkeleton num={23} />
}
