import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Privacy — TZ tab 36, /privacy. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(36)

export default function Page() {
  return <PageSkeleton num={36} />
}
