import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Contact — TZ tab 34, /contact. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(34)

export default function Page() {
  return <PageSkeleton num={34} />
}
