import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** huntDRIVE — TZ tab 05, /huntdrive. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(5)

export default function Page() {
  return <PageSkeleton num={5} />
}
