import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** LoadHunter — TZ tab 03, /loadhunter. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(3)

export default function Page() {
  return <PageSkeleton num={3} />
}
