import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Guides — TZ tab 25, /guides. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(25)

export default function Page() {
  return <PageSkeleton num={25} />
}
