import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Customers — TZ tab 21, /customers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(21)

export default function Page() {
  return <PageSkeleton num={21} />
}
