/**
 * Generate AVIF + WebP siblings for every raster in public/figma/**.
 * The <Img> component (src/components/site/Img.tsx) serves them via <picture>
 * with the original PNG kept as the universal fallback — so this is additive
 * and safe: no existing asset is modified or removed.
 *
 * Run:  npm run transcode         (skips up-to-date siblings)
 *       npm run transcode -- --force
 *
 * Tune quality below; WebP q88 / AVIF q64 are visually lossless for these UI
 * screenshots and gradients while cutting ~50–75% of the bytes.
 */
import { readdir, stat, writeFile, mkdir } from "node:fs/promises"
import { join, extname } from "node:path"
import sharp from "sharp"

const ROOT = new URL("../public/figma/", import.meta.url).pathname
const PUBLIC = new URL("../public/", import.meta.url).pathname
const MANIFEST = new URL("../src/generated/img-dimensions.ts", import.meta.url).pathname
const FORCE = process.argv.includes("--force")
const WEBP = { quality: 88, effort: 5 }
const AVIF = { quality: 64, effort: 4 } // effort 4 keeps encode time bounded

async function walk(dir) {
  const out = []
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) out.push(...(await walk(p)))
    else if (/\.(png|jpe?g)$/i.test(e.name)) out.push(p)
  }
  return out
}

const fresh = async (src, out) => {
  if (FORCE) return false
  try {
    return (await stat(out)).mtimeMs >= (await stat(src)).mtimeMs
  } catch {
    return false
  }
}

const files = await walk(ROOT)
let srcBytes = 0
let webpBytes = 0
let avifBytes = 0
let made = 0
let skipped = 0
const dims = {} // public URL ("/figma/x.png") → [width, height]

for (const src of files) {
  const base = src.slice(0, -extname(src).length)
  const webpOut = base + ".webp"
  const avifOut = base + ".avif"
  const sBytes = (await stat(src)).size
  srcBytes += sBytes

  // record intrinsic dimensions so <Img> can set width/height (prevents CLS)
  const meta = await sharp(src).metadata()
  const url = "/" + src.slice(PUBLIC.length)
  dims[url] = [meta.width, meta.height]

  if (!(await fresh(src, webpOut))) {
    await sharp(src).webp(WEBP).toFile(webpOut)
    made++
  } else skipped++
  if (!(await fresh(src, avifOut))) {
    await sharp(src).avif(AVIF).toFile(avifOut)
    made++
  } else skipped++

  webpBytes += (await stat(webpOut)).size
  avifBytes += (await stat(avifOut)).size
}

// emit the dimensions manifest consumed by src/components/site/Img.tsx
await mkdir(new URL("../src/generated/", import.meta.url).pathname, { recursive: true })
const sorted = Object.fromEntries(Object.entries(dims).sort())
await writeFile(
  MANIFEST,
  "// AUTO-GENERATED by scripts/transcode-images.mjs — do not edit.\n" +
    "// Intrinsic pixel dimensions of every /figma raster, so <Img> can set\n" +
    "// width/height and reserve layout space (prevents CLS).\n" +
    "export const IMG_DIMENSIONS: Record<string, [number, number]> = " +
    JSON.stringify(sorted, null, 2) +
    "\n",
)

const mb = (b) => (b / 1024 / 1024).toFixed(2)
const pct = (a, b) => (((a - b) / a) * 100).toFixed(0)
console.log(`\nTranscoded ${files.length} rasters  (made ${made}, skipped ${skipped})`)
console.log(`  Wrote dimensions manifest: ${Object.keys(dims).length} entries`)
console.log(`  PNG/JPG total : ${mb(srcBytes)} MB`)
console.log(`  WebP total    : ${mb(webpBytes)} MB  (−${pct(srcBytes, webpBytes)}%)`)
console.log(`  AVIF total    : ${mb(avifBytes)} MB  (−${pct(srcBytes, avifBytes)}%)`)
console.log(
  `  Modern browsers download AVIF→WebP: ~${mb(avifBytes)} MB instead of ${mb(srcBytes)} MB.\n`,
)
