/**
 * Brand Registry - TZ §14.3.
 *
 * "Юридическое название, домены, контакты, социальные ссылки, copyright и
 * утверждённые логотипы." One record, read by the header, the footer, the
 * Organization markup and the sitemap, so the legal entity is corrected in one
 * place when it arrives rather than in nine.
 *
 * `legalEntity` is null on purpose. §18.3 makes the entity behind a commercial
 * claim something the owner confirms, and the copyright line is exactly such a
 * claim. Until it is confirmed the line carries the trading name, and
 * `assertPublishable` in ./index.ts lists it as owed.
 */

export type Logo = {
  /** Path under /public. */
  src: string
  /** Approved use: what this file may appear on. */
  use: "light-surface" | "dark-surface"
  width: number
  height: number
}

export const BRAND = {
  name: "LoadHunter",
  /** §1.1 - the category, not a slogan. */
  category: "AI-powered Freight Operations Ecosystem",
  legalEntity: null as string | null,
  domain: "https://loadhunt.ai",
  copyright: "© 2026 LoadHunter. All rights reserved.",
  contact: {
    email: "support@loadhunter.io",
    phone: "+1 312 878 9795",
    phoneHref: "+13128789795",
    region: "United States",
  },
  socials: [
    { label: "Telegram", href: "https://t.me/loadhunterextension" },
    { label: "Instagram", href: "https://www.instagram.com/loadhunter.io/" },
    { label: "YouTube", href: "https://www.youtube.com/channel/UC5-wNvj8HpG-9fZgFa88SXw" },
    { label: "X", href: "https://x.com/load_hunt" },
  ],
  logos: {
    iconLight: { src: "/brand/logo-icon.svg", use: "light-surface", width: 24, height: 24 },
    iconDark: { src: "/brand/logo-icon-white.svg", use: "dark-surface", width: 24, height: 24 },
    wordmarkLight: { src: "/brand/logo-text.svg", use: "light-surface", width: 116, height: 19 },
    wordmarkDark: { src: "/brand/logo-text-white.svg", use: "dark-surface", width: 116, height: 19 },
  } satisfies Record<string, Logo>,
  /**
   * §10.1 - the social image every indexable page carries.
   *
   * Generated by `app/opengraph-image.tsx` at build time, so it is a real file
   * in the output rather than a request-time render. A page overrides it by
   * setting its own `openGraph.images`; the CMS field §10.1 defines is what
   * will do that per page.
   */
  socialImage: { url: "/opengraph-image", width: 1200, height: 630 },
  /** §26.4 - the category statement, one sentence, no product names. */
  statement:
    "One connected system for finding freight, running operations, keeping drivers moving, getting paid and seeing the business clearly.",
  /** §19 - market framing, first commercial region and the P0 language. */
  region:
    "Built for trucking and freight operations worldwide. First commercial region: United States. Site language: US English.",
  /**
   * §18.3 - the trademark independence line. It names third-party load boards,
   * which is permitted precisely because the sentence disclaims association;
   * §7.2 forbids using their marks anywhere else.
   */
  trademarkDisclaimer:
    "LoadHunter is an independent product and is not affiliated with, endorsed by or sponsored by DAT Solutions, Truckstop, TruckSmarter or other third-party load-board providers. Product names and trademarks belong to their respective owners.",
} as const

/** Kept as its own export: the sitemap, robots and metadata all need only this. */
export const SITE_URL = BRAND.domain
