import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Dispatchers — TZ tab 14, /dispatchers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(14)

export default function Page() {
  return <PageSkeleton num={14} />
}
