import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Brokers — TZ tab 10, /brokers. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(10)

export default function Page() {
  return <PageSkeleton num={10} />
}
