import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Integrations — TZ tab 20, /integrations. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(20)

export default function Page() {
  return <PageSkeleton num={20} />
}
