import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Status — TZ tab 30, /status. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(30)

export default function Page() {
  return <PageSkeleton num={30} />
}
