import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Blog — TZ tab 24, /blog. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(24)

export default function Page() {
  return <PageSkeleton num={24} />
}
