import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Accessibility — TZ tab 45, /accessibility. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(45)

export default function Page() {
  return <PageSkeleton num={45} />
}
