import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Marketplace — TZ tab 08, /marketplace. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(8)

export default function Page() {
  return <PageSkeleton num={8} />
}
