import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Compare — TZ tab 27, /compare. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(27)

export default function Page() {
  return <PageSkeleton num={27} />
}
