import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** huntTMS — TZ tab 04, /hunttms. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(4)

export default function Page() {
  return <PageSkeleton num={4} />
}
