import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** huntPAY — TZ tab 06, /huntpay. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(6)

export default function Page() {
  return <PageSkeleton num={6} />
}
