import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** huntOS — TZ tab 07, /huntos. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(7)

export default function Page() {
  return <PageSkeleton num={7} />
}
