import { PageSkeleton, pageMetadata } from "@/components/PageSkeleton"

/** Live Tracking — TZ tab 11, /live-tracking. Generated by scripts/gen-routes.mjs. */
export const metadata = pageMetadata(11)

export default function Page() {
  return <PageSkeleton num={11} />
}
